# config_final.yaml
device: cuda:0
data: /home/ma/ma_ma/ma_tofuchs/Graph-WaveNet-Mannheim/Datasets/Mannheim/train_data/x6y1
adjdata: /home/ma/ma_ma/ma_tofuchs/Graph-WaveNet-Mannheim/adj_sparse_1.csv
adjtype: doubletransition
gcn_bool: true
aptonly: false
addaptadj: true
randomadj: true
evaluate_only: true
seq_length: 6
nhid: 43
in_dim: 2
num_nodes: 25
batch_size: 253
learning_rate: 0.000533718397820362
dropout: 0.5384147073000745
weight_decay: 0.00000365560764367765
epochs: 1000
print_every: 50
save: /home/ma/ma_ma/ma_tofuchs/Graph-WaveNet-Mannheim/models
expid: 7
diffusion_steps: 2
#checkpoint: /pfs/work9/workspace/scratch/ma_tofuchs-GraphWave-Seminar/models/best/best_vloss_94.79.pth
#plotheatmap: True